### ISSUE TITLE
References to crontab in the Linux installer should be removed

### ISSUE THREAD

**Issue by nealg1** [Rise-Vision/player-native#12]
<b>What happens now:</b> Currently as part of the Linux script, there is a function to clear crontab, even though we don't use it any longer.  This has the effect of anybody else using it having their jobs being erased.

<b>What should happen</b> We shouldn't be clearing crontab as part of the startup script so that other jobs are maintained.

**Comment by hcs0** [comment]
I see no ref to clear crontab in the new script, closing unless there is one. @fjvallarino @tejohnso
